# Each Location may have the following keys:
#
# library_code   - ldpd code for library, used in ldpd hours
# location_code  - ldpd code for location, used in ldpd map pages
# links          - arbitary list of links to show on location page
# category       - "physical" or "no_location", physical gets location page
# location       - string used for substring lookup against bib's location
# found_in       - used to print physical address on location page
#
--- 
- :library_code: butler
  :location_code: butler
  :links: 
  :category: physical
  :location: African Studies
  :found_in: |-
    African Studies Reading Room
    607 Butler Library

- :library_code: butler
  :location_code: butler
  :links: 
  :category: physical
  :location: Comp Lit
  :found_in: |-
    Comp Lit & Society Reading Room
    615 Butler (Non-Circ)

- :library_code: butler
  :location_code: butler
  :links: 
  :category: physical
  :location: Edward Said
  :found_in: |-
    Edward Said Reading Rm
    616 Butler (Non-Circulating)

- :library_code: butler
  :location_code: butler
  :links: 
  :category: physical
  :location: Ancient/Medieval
  :found_in: |-
    Ancient/Medieval Reading Room
    603 Butler Library

- :library_code: butler
  :location_code: butler
  :links: 
  :category: physical
  :location: Graphic Novels Collection
  :found_in: |-
    Milstein 406a, 406, and 409
    Butler, 4th Floor, West
    
- :library_code: avery
  :location_code: avery
  :links: 
    Home Page: https://library.columbia.edu/locations/avery.html
    Floorplans: https://library.columbia.edu/locations/avery/floorplans.html
  :category: physical
  :location: Avery
  :found_in: |-
    Avery Architectural & Fine Arts Library
    
    Avery Hall


- :library_code: avery-art-properties
  :location_code: avery-art-properties
  :links: 
    Home Page: https://library.columbia.edu/locations/avery/art-properties.html
    Floorplans: https://library.columbia.edu/locations/avery/floorplans.html
  :category: physical
  :location: Avery Art Properties
  :found_in: |-
    Avery Architectural & Fine Arts Library

    300 Avery Hall


- :library_code: avery-drawings-archives
  :location_code: avery-drawings-archives
  :links: 
    Home Page: https://library.columbia.edu/locations/avery/da.html
    Floorplans: https://library.columbia.edu/locations/avery/floorplans.html
  :category: physical
  :location: Avery Drawings & Archives
  :found_in: |-
    Avery Architectural & Fine Arts Library

    Avery Hall


- :library_code: avery-classics
  :location_code: avery-classics
  :links: 
    Home Page: https://library.columbia.edu/locations/avery/classics.html
    Floorplans: https://library.columbia.edu/locations/avery/floorplans.html
  :category: physical
  :location: Avery Classics
  :found_in: |-
    Avery Architectural & Fine Arts Library

    Avery Hall


- :library_code: barnard
  :location_code: barnard
  :links: 
    Home Page: https://library.barnard.edu
    Stacks Guide: https://library.barnard.edu/stacks-guide
  :category: physical
  :location: Barnard
  :found_in: |-
    Barnard College Library
    
    The Milstein Center for Teaching and Learning

# - :library_code: barnard
#   :location_code: barnard
#   :links: 
#     Home Page: http://library.barnard.edu/
#     Stacks Guide: https://library.barnard.edu/stacks-guide
#   :category: physical
#   :location: Barnard Archives
#   :found_in: |-
#     Barnard College Library
# 
#     The Milstein Center for Teaching and Learning
# 
# - :library_code: barnard
#   :location_code: barnard
#   :links: 
#     Home Page: http://library.barnard.edu/
#     Stacks Guide: https://library.barnard.edu/stacks-guide
#   :category: physical
#   :location: Barnard Rare
#   :found_in: |-
#     Barnard College Library
# 
#     The Milstein Center for Teaching and Learning
# 
# - :library_code: barnard
#   :location_code: barnard
#   :links: 
#     Home Page: http://library.barnard.edu/
#     Stacks Guide: https://library.barnard.edu/stacks-guide
#   :category: physical
#   :location: Barnard Special
#   :found_in: |-
#     Barnard College Library
# 
#     The Milstein Center for Teaching and Learning
# 

- :library_code: burke
  :location_code: burke
  :links: 
    Home Page: https://library.columbia.edu/locations/burke.html
    Location Guide: https://library.columbia.edu/content/dam/libraryweb/floorplans/burke_location_guide.pdf
  :category: physical
  :location: Burke
  :found_in: |-
    Union Theological Seminary, Burke Library
    
    3041 Broadway @ 121st Street

- :library_code: business
  :location_code: business
  :links: 
    Home Page: https://library.columbia.edu/locations/business.html
    Floorplans: https://library.columbia.edu/content/dam/libraryweb/floorplans/business_floorplan.pdf
  :category: physical
  :location: Business
  :found_in: |-
    Business & Economics Library
    
    130 Uris

- :library_code: butler
  :location_code: butler
  :links: 
    Home Page: https://library.columbia.edu/locations/butler.html
    Call Number Guide: https://library.columbia.edu/content/dam/libraryweb/locations/butler/Butler_Stacks_Guide_2016.pdf
  :category: physical
  :location: Butler
  :found_in: |-
    Butler Library
    
    535 West 114th Street

- :library_code: butler
  :location_code: butler
  :links: 
    Home Page: https://library.columbia.edu/locations/butler/media-services.html
  :category: physical
  :location: Butler Media
  :found_in: |-
    Butler Media Services
    
    Main Circulation Desk, 3rd Floor
- :library_code: butler
  :location_code: pmrr
  :links: 
    Home Page: https://library.columbia.edu/locations/pmrr.html
  :category: physical
  :location: Butler Microforms
  :found_in: |-
    Butler Periodicals & Microforms Reading Room
    
    401 Butler Library

- :library_code: butler
  :location_code: pmrr
  :links: 
    Home Page: https://library.columbia.edu/locations/pmrr.html
  :category: physical
  :location: Butler Periodicals
  :found_in: |-
    Butler Periodicals & Microforms Reading Room
    
    401 Butler Library

- :library_code: butler-reference
  :location_code: butler-reference
  :links: 
    Call Number Guide: https://library.columbia.edu/content/dam/libraryweb/locations/butler/Butler%20Reference/301%26310.pdf
    Home Page: https://library.columbia.edu/locations/butler-reference.html
  :category: physical
  :location: Butler Reference Desk
  :found_in: |-
    Butler Reference
    
    301 Butler Library

- :library_code: butler-24 
  :location_code: butler 
  :links: 
    Call Number Guide: https://library.columbia.edu/content/dam/libraryweb/locations/butler/Butler%20Reference/301%26310.pdf
    Home Page: https://library.columbia.edu/locations/butler-reference.html
  :category: physical
  :location: Butler Reference
  :found_in: |-
    Butler Reference

    301 Butler Library
- :library_code: butler
  :location_code: butler-reserves
  :links: 
    Home Page: https://library.columbia.edu/locations/butler-reserves.html
  :category: physical
  :location: Butler Reserves
  :found_in: |-
    Circulation Desk
    3rd Floor Butler Library
- :library_code: butler
  :location_code: butler
  :links: 
    Home Page: https://library.columbia.edu/locations/butler-circulation.html
    Floorplan: https://library.columbia.edu/locations/butler/floorplan.html
    Call Number Guide: https://library.columbia.edu/content/dam/libraryweb/locations/butler/Butler_Stacks_Guide_2016.pdf
  :category: physical
  :location: Butler Stacks
  :found_in: |-
    Butler Circulation
    
    3rd Floor Butler Library
- :links: 
    Home Page: mailto:klg39@columbia.edu
  :category: no_location
  :location: Dakhla Library
  :found_in: |-
    Dakhla Oasis, Egypt.
    Not available on campus. Contact Karen Green klg39@columbia.edu with any questions.
- :library_code: butler
  :location_code: butler
  :links: 
  :category: physical
  :location: Early Modern/Modern Europe
  :found_in: |-
    Early Modern/Modern Europe Reading Room
    504 Butler Library
- :library_code: eastasian
  :location_code: eastasian
  :links: 
    Home Page: https://library.columbia.edu/locations/eastasian.html
  :category: physical
  :location: East Asian
  :found_in: |-
    Starr East Asian Library
    
    300 Kent Hall
- :library_code: dhc
  :location_code: dhc
  :links: 
    Home Page: https://library.columbia.edu/locations/dhc.html
  :category: physical
  :location: Electronic Text Service
  :found_in: |-
    Electronic Text Service
    
    305 Butler Library

- :library_code: health-sciences
  :location_code: health-sciences
  :links: 
    Home Page: https://library.cumc.columbia.edu/
    Stacks Floorplan: https://library.cumc.columbia.edu/lower-level-2-floorplan
  :category: physical
  :location: Health Sciences
  :found_in: |-
    Health Sciences Library
    
    701 West 168th Street

- :library_code: health-sciences
  :location_code: health-sciences
  :links: 
    Home Page: https://library.cumc.columbia.edu/
    Library Floorplan: https://library.cumc.columbia.edu/library-floorplan
  :category: physical
  :location: Health Sciences Reserve
  :found_in: |-
    Health Sciences Library, Reserves

    701 West 168th Street
- :library_code:
  :location_code: health-sciences
  :links: 
    Home Page: https://library.cumc.columbia.edu/archives
    Library Floorplan: https://library.cumc.columbia.edu/lower-level-1-floorplan
  :category: physical
  :location: Health Sciences Spec Coll
  :found_in: |-
    Health Sciences Library, Special Collections

    701 West 168th Street
- :links: {}

  :category: no_location
  :location: Health Sciences Web
  :found_in: |-
    Electronic Resource.
    Look for "Online Link" in record.
- :library_code: butler
  :location_code: butler
  :links: 
  :category: physical
  :location: Islamic Studies
  :found_in: |-
    Islamic Studies Reading Room
    602 Butler Library
- :library_code: journalism
  :location_code: journalism
  :links: 
    Home Page: https://library.columbia.edu/locations/journalism.html
  :category: physical
  :location: Journalism
  :found_in: |-
    Journalism Library
    
    203 Journalism
- :library_code: butler
  :location_code: butler
  :links: 
  :category: physical
  :location: Latin American Studies
  :found_in: |-
    Latin American Studies Reading Room
    503 Butler Library

- :library_code: lehman
  :location_code: lehman
  :links: 
    Home Page: https://library.columbia.edu/locations/lehman.html
    Floorplans: https://library.columbia.edu/locations/lehman/floorplan.html
  :category: physical
  :location: Lehman
  :found_in: |-
    Lehman Social Sciences Library
    
    300 International Affairs

- :library_code: lehman
  :location_code: lehman
  :links: 
    Home Page: https://library.columbia.edu/locations/lehman.html
    Floorplans: https://library.columbia.edu/locations/lehman/floorplan.html
  :category: physical
  :location: Business Collection, Lehman
  :found_in: |-
    Lehman Social Sciences Library

    300 International Affairs

- :library_code: dssc-data
  :location_code: dssc-data
  :links: 
    Home Page: https://library.columbia.edu/locations/dssc/data/service.html
  :category: physical
  :location: Lehman Data Service
  :found_in: |-
    Electronic Data Service
    
    215 International Affairs
- :library_code: lehman
  :location_code: lehman
  :links: 
    Home Page: https://library.columbia.edu/locations/maps.html
  :category: physical
  :location: Lehman Map Room
  :found_in: |-
    Lehman Map Room
    
    300 International Affairs

- :library_code: lehman
  :location_code: lehman
  :links: 
    Home Page: https://library.columbia.edu/locations/usgd.html
  :category: physical
  :location: Lehman US Government Documents
  :found_in: |-
    US Government Documents
    
    300 International Affairs
- :links: {}

  :category: no_location
  :location: LibraryWeb
  :found_in: |-
    Electronic Resource.
    Look for "Online Link" in record.
- :library_code: math
  :location_code: math
  :links: 
    Home Page: https://library.columbia.edu/locations/math.html
  :category: physical
  :location: Math-Science
  :found_in: |-
    Mathematics/Science Library
    
    303 Mathematics
- :library_code: math
  :location_code: math
  :links: 
    Home Page: https://library.columbia.edu/locations/math.html
  :category: physical
  :location: Mathematics
  :found_in: |-
    Mathematics/Science Library
    
    303 Mathematics
- :library_code: butler-24
  :location_code: butler
  :links: 
    Home Page: https://library.columbia.edu/locations/undergraduate.html
    Shelving Guide: https://library.columbia.edu/locations/undergraduate/call_number_guide.html
  :category: physical
  :location: Milstein
  :found_in: |-
    Milstein Library (Undergraduate Library)
    
    Butler Library Rooms on the 2nd, 3rd & 4th floors
- :library_code: butler
  :location_code: butler
  :links: 
  :category: physical
  :location: Modern & Comparative Studies
  :found_in: |-
    Modern & Comparative Studies Reading Room
    504 Butler Library
- :library_code: butler
  :location_code: butler
  :links: 
  :category: physical
  :location: Moral & Political Theory
  :found_in: |-
    Moral & Political Theory Reading Room
    504 Butler Library

- :library_code: music
  :location_code: music
  :links: 
    Home Page: https://library.columbia.edu/locations/music.html
  :category: physical
  :location: Music
  :found_in: |-
    Music & Arts Library
    
    701 Dodge

- :links: 
    Home Page: https://library.columbia.edu/find/request/off-site.html
  :category: no_location
  :location: Offsite
  :found_in: |-
    Offsite Shelving Facility (ReCap)
    
    Use green "Get From Offsite" link in record to retrieve items
    Non-affiliates please contact LIO for access, lio@columbia.edu or (212) 854-7309


- :library_code: butler
  :location_code: butler
  :links: 
  :category: physical
  :location: Papyrus & Epigraphy
  :found_in: |-
    Papyrus & Epigraphy
    604 Butler Library
- :library_code: rbml
  :location_code: rbml
  :links: 
    Home Page: https://library.columbia.edu/locations/rbml.html
  :category: physical
  :location: Rare Book
  :found_in: |-
    Rare Book & Manuscript Library
    
    6th Floor East, Butler Library
- :library_code: science-engineering
  :location_code: science-engineering
  :links: 
    Home Page: https://library.columbia.edu/locations/science-library.html
  :category: physical
  :location: Science
  :found_in: |-
      401 Northwest Corner Building

      550 West 120th Street
- :library_code: social-work
  :location_code: social-work
  :links: 
    Home Page: https://library.columbia.edu/locations/social-work.html
  :category: physical
  :location: Social Work
  :found_in: |-
    Social Work Library
    
    1255 Amsterdam Avenue @ 122nd Street
- :library_code: butler
  :location_code: butler
  :links: 
  :category: physical
  :location: South Asian Studies
  :found_in: |-
    South Asian Studies Reading Room
    601 Butler Library
- :library_code: butler
  :location_code: butler
  :links: 
  :category: physical
  :location: US History & Literature
  :found_in: |-
    US History & Literature Reading Room
    502 Butler Library
- :library_code: rbml
  :location_code: rbml
  :links: 
    Home Page: https://library.columbia.edu/locations/cuarchives.html
  :category: physical
  :location: University Archives
  :found_in: |-
    Columbia University Archives
    
    6th Floor East, Butler Library
- :library_code: law
  :location_code: law
  :links: 
    Home Page: https://web.law.columbia.edu/library
  :category: physical
  :location: Law
  :found_in: |-
    Arthur W. Diamond Law Library

    Jerome Greene Hall, 3rd floor

- :library_code: dhc
  :location_code: digital-scholarship
  :links: 
    Home Page: http://library.columbia.edu/locations/dhc.html
  :category: physical
  :location: Digital Scholarship Services
  :found_in: |-
    Digital Scholarship Services

    305 Butler Library

- :library_code: science-engineering
  :location_code: science-engineering
  :links: 
    Home Page: https://library.columbia.edu/locations/dsc.html
    Directions: https://library.columbia.edu/locations/science-library/directions.html
  :category: physical
  :location: Digital Science Center
  :found_in: |-
    Digital Science Center

    401 Northwest Corner Building

- :library_code: lehman
  :location_code: lehman
  :links: 
    Home Page: https://library.columbia.edu/locations/dssc.html
  :category: physical
  :location: Digital Social Science Center
  :found_in: |-
    Digital Social Science Center

    300 International Affairs

- :library_code: music
  :location_code: music
  :links: 
    Home Page: https://library.columbia.edu/locations/music/music_lab.html
  :category: physical
  :location: Digital Music Lab
  :found_in: |-
    Digital Music Lab

    701 Dodge




