absorbed:
    -   tag: 780
        ind1: :all
        ind2: '5'
        display: abcdghkmnst
        search: t
absorbed_in_part:
    -   tag: 780
        ind1: :all
        ind2: '6'
        display: abcdghkmnst
        search: t
absorbed_by:
    -   tag: 785
        ind1: :all
        ind2: '4'
        display: abcdghkmnst
        search: t
absorbed_in_part_by:
    -   tag: 785
        ind1: :all
        ind2: '5'
        display: abcdghkmnst
        search: t
arrangement:
    -   tag: 351
        display: abc
author:
    -   tag: 100
        display: abcdefgjklnpqtu
        search: abcdq
    -   tag: 110
        display: abcdefgjklnpqtu
        search: abcdefgjklnpqtu
    -   tag: 111
        display: acdefgjklnpqtu
        search: acdefgjklnpqtu
author_other:
    -   tag: 700
        display: abcdefghijklmnopqrstux
        search: abcdq
    -   tag: 710
        display: abcdefghiklmnoprstux
        search: abcdefghiklmnoprstux
    -   tag: 711
        display: acdefghijklnpqstux
        search: acdefghijklnpqstux
biographical_historical_note:
    -   tag: 545
        display: ab
cast:
    -   tag: 511
        ind1: '1'
        ind2: :all
        display: a
changed_back_to:
    -   tag: 785
        ind1: :all
        ind2: '8'
        display: abcdghkmnst
        search: t
constituent_items:
    -   tag: 789
        display: 1livtncdpo
contents:
    -   tag: 505
        display: agrtu
        split: '--'
continued_by:
    -   tag: 785
        ind1: :all
        ind2: '0'
        display: abcdghkmnst
        search: t
continued_in_part_by:
    -   tag: 785
        ind1: :all
        ind2: '1'
        display: abcdghkmnst
        search: t
continues:
    -   tag: 780
        ind1: :all
        ind2: '0'
        display: abcdghkmnst
        search: t
continues_in_part:
    -   tag: 780
        ind1: :all
        ind2: '1'
        display: abcdghkmnst
        search: t
credits:
    -   tag: 508
        display: a
description:
    -   tag: 300
        display: abcefg3
    -   tag: 305
        display: abcdefmn
    -   tag: 308
        display: abcdef
    -   tag: 340
        display: abcdefhi
edition:
    -   tag: 250
        display: ab
finding_aid:
    -   tag: 555
        ind1: '0'
        ind2: :all
        display: abcdu3
formed_by_the_union_of:
    -   tag: 780
        ind1: :all
        ind2: '4'
        display: abcdghkmnst
        search: t
frequency:
    -   tag: 310
        display: ab
    -   tag: 321
        display: ab
in:
    -   tag: 773
        display: abdghkmnpqrstuxyz
issues_published:
    -   tag: 362
        display: a
ISN:
    -   tag: '020'
        display: ac
    -   tag: '022'
        display: a
    -   tag: '024'
        ind1: '0123478'
        ind2: :all
        display: ac
ISBN:
    -   tag: '020'
        display: ac
ISSN:
    -   tag: '022'
        display: a
LCCN:
    -   tag: '010'
        display: a
language:
    -   tag: 546
        display: ab3
map_format:
    -   tag: 255
        display: abcde
    -   tag: 342
        display: abcdefghijklnopqrstuvw
    -   tag: 343
        display: abcdefghi
    -   tag: 352
        display: abcdefgi
    -   tag: 514
        display: abcdefghijkm
merged_with_to_form:
    -   tag: 785
        ind1: :all
        ind2: '7'
        display: abcdghkmnst
        search: t
notes:
    -   tag: 500
        display: a
    -   tag: 501
        display: a
    -   tag: 502
        display: a
    -   tag: 503
        display: a
    -   tag: 504
        display: ab
    -   tag: 508
        display: a
    -   tag: 513
        display: ab
    -   tag: 518
        display: a3
    -   tag: 521
        display: ab3
    -   tag: 522
        display: a
    -   tag: 523
        display: ab
    -   tag: 525
        display: a
    -   tag: 527
        display: a
    -   tag: 530
        display: abcd3
    -   tag: 534
        display: abcefklmnopt
    -   tag: 535
        display: abcdg3
    -   tag: 537
        display: a
    -   tag: 547
        display: a
    -   tag: 550
        display: a
    -   tag: 556
        display: a
    -   tag: 565
        display: abcde3
    -   tag: 567
        display: a
    -   tag: 580
        display: a
    -   tag: 581
        display: a3
    -   tag: 582
        display: a
    -   tag: 584
        display: ab
    -   tag: 586
        display: a3
    -   tag: 590
        display: a
notes_book:
    -   tag: 500
        display: a
    -   tag: 501
        display: a
    -   tag: 502
        display: a
    -   tag: 503
        display: a
    -   tag: 504
        display: ab
    -   tag: 513
        display: ab
    -   tag: 515
        display: a
    -   tag: 521
        display: ab3
    -   tag: 522
        display: a
    -   tag: 525
        display: a
    -   tag: 530
        display: abcd3
    -   tag: 534
        display: abcefklmnopt
    -   tag: 586
        display: a3
    -   tag: 590
        display: a
notes_manuscript_archive:
    -   tag: 500
        display: a
    -   tag: 580
        display: a
    -   tag: 581
        display: a3
    -   tag: 586
        display: a3
    -   tag: 590
        display: a
notes_map_globe:
    -   tag: 500
        display: a
    -   tag: 501
        display: a
    -   tag: 504
        display: ab
    -   tag: 515
        display: a
    -   tag: 521
        display: ab3
    -   tag: 522
        display: a
    -   tag: 525
        display: a
    -   tag: 530
        display: abcd3
    -   tag: 534
        display: abcefklmnopt
    -   tag: 580
        display: a
    -   tag: 581
        display: a3
    -   tag: 586
        display: a3
    -   tag: 590
        display: a
notes_music_recording:
    -   tag: 254
        display: a
    -   tag: 500
        display: a
    -   tag: 508
        display: a
    -   tag: 518
        display: a3
    -   tag: 590
        display: a
notes_serial:
    -   tag: 500
        display: a
    -   tag: 501
        display: a
    -   tag: 504
        display: ab
    -   tag: 515
        display: a
    -   tag: 521
        display: ab3
    -   tag: 525
        display: a
    -   tag: 530
        display: abcd3
    -   tag: 534
        display: abcefklmnopt
    -   tag: 535
        display: abcdg3
    -   tag: 547
        display: a
    -   tag: 550
        display: a
    -   tag: 580
        display: a
    -   tag: 590
        display: a
notes_video:
    -   tag: 500
        display: a
    -   tag: 518
        display: a3
    -   tag: 521
        display: ab3
    -   tag: 530
        display: abcd3
    -   tag: 534
        display: abcefklmnopt
    -   tag: 550
        display: a
    -   tag: 586
        display: a3
    -   tag: 590
        display: a
performers:
    -   tag: 511
        ind1: '0'
        ind2: :all
        display: a
provenance:
    -   tag: 561
        display: a3
publisher:
    -   tag: 260
        display: abcefg3
    -   tag: 261
        display: abdef
    -   tag: 262
        display: abckl
    -   tag: 264
        display: abc3
    -   tag: 270
        display: abcdefghijklmnpqrz
publisher_no:
    -   tag: '028'
        display: ab
related_to:
    -   tag: 787
        display: abcdghikmnorst
reproduction_note:
    -   tag: 533
        display: abcdefmn3
restrictions:
    -   tag: 506
        display: abcdeu3
    -   tag: 540
        display: abcdu3
scale:
    -   tag: 507
        display: abce
separated_from:
    -   tag: 780
        ind1: :all
        ind2: '7'
        display: abcdghkmnst
        search: t
series:
    -   tag: 490
        ind1: '0'
        ind2: :all
        display: alvx3
    -   tag: 800
        display: abcdefghklmnopqrstuv3
    -   tag: 810
        display: abcdefghklmnoprstuv3
    -   tag: 811
        display: acdefghklnpqstuv3
    -   tag: 830
        display: adfghklmnoprstv3
        search: adfghklmnoprst
    -   tag: 840
        display: ahv
split_into:
    -   tag: 785
        ind1: :all
        ind2: '6'
        display: abcdghkmnst
        search: t
standard_no:
    -   tag: '024'
        ind1: '0123478'
        ind2: :all
        display: ac
subject_genre:
    -   tag: 655
        ind1: :all
        ind2: :all
        display: abcvxyz
subject_LC:
    -   tag: 600
        ind1: :all
        ind2: '0'
        display: abcdefghklmnopqrstuvxyz
    -   tag: 610
        ind1: :all
        ind2: '0'
        display: abcdefghklmnoqrstuvxyz
    -   tag: 611
        ind1: :all
        ind2: '0'
        display: acdefghklnpqstuvxyz
    -   tag: 630
        ind1: :all
        ind2: '0'
        display: adfghklmnoprstvxyz
    -   tag: 650
        ind1: :all
        ind2: '0'
        display: abcdvxyz
    -   tag: 651
        ind1: :all
        ind2: '0'
        display: avxyz
subject_mesh:
    -   tag: 600
        ind1: :all
        ind2: '2'
        display: abcdefghklmnopqrstuvxyz
    -   tag: 610
        ind1: :all
        ind2: '2'
        display: abcdefghklmnoqrstuvxyz
    -   tag: 611
        ind1: :all
        ind2: '2'
        display: acdefghklnpqstuvxyz
    -   tag: 630
        ind1: :all
        ind2: '2'
        display: adfghklmnoprstvxyz
    -   tag: 650
        ind1: :all
        ind2: '2'
        display: abcdvxyz
    -   tag: 651
        ind1: :all
        ind2: '2'
        display: avxyz
summary:
    -   tag: 520
        display: abc
superseded_by:
    -   tag: 785
        ind1: :all
        ind2: '2'
        display: abcdghkmnst
        search: t
superseded_in_part_by:
    -   tag: 785
        ind1: :all
        ind2: '3'
        display: abcdghkmnst
        search: t
supersedes:
    -   tag: 780
        ind1: :all
        ind2: '2'
        display: abcdghkmnst
        search: t
supersedes_in_part:
    -   tag: 780
        ind1: :all
        ind2: '3'
        display: abcdghkmnst
        search: t
system_details:
    -   tag: 538
        display: aiu
title:
    -   tag: 245
        display: abcfghknps
title_added:
    -   tag: 246
        ind1: '01'
        ind2: '5'
        display: abfghinp
title_caption:
    -   tag: 246
        ind1: '01'
        ind2: '6'
        display: abfghinp
title_cover:
    -   tag: 246
        ind1: '01'
        ind2: '4'
        display: abfghinp
title_distinctive:
    -   tag: 246
        ind1: '01'
        ind2: '2'
        display: abfghinp
title_other:
    -   tag: 246
        display: abfghinp
        ind1: '01'
        ind2: ' 3'
    -   tag: 247
        display: abfghnp
    -   tag: 730
        display: adfghklmnoprst
    -   tag: 740
        display: ahnp
title_parallel:
    -   tag: 246
        ind1: '01'
        ind2: '1'
        display: abfghinp
title_running:
    -   tag: 246
        ind1: '01'
        ind2: '7'
        display: abfghinp
title_spine:
    -   tag: 246
        ind1: '01'
        ind2: '8'
        display: abfghinp
title_uniform:
    -   tag: 240
        display: adfghklmnoprs
    -   tag: 130
        display: adfghklmnoprst
