site:
  manage:
    - gb8
    - sam119

item_alerts:
  manage:
      - aj204
      - am447
      - aom1
      - ar34
      - asb2154
      - at2186
      - avh1
      - bas3
      - bb145
      - bl23
      - bw12
      - cak2158
      - cm119    
      - cmm2169
      - cmm64
      - cs151
      - cw2165
      - dm2764
      - ead1
      - ecg2
      - erg2104
      - fd2102
      - fh2238
      - gb8
      - hk368
      - hs2148
      - jc677
      - jc93
      - jf2156
      - jlc4
      - jm86
      - jrs19
      - jss8
      - jt2118
      - jt628
      - jwb3
      - jws824
      - kd2145
      - kh33
      - klg19
      - kmk3
      - krc1
      - lh2112
      - ll162
      - mc3395
      - mcb2212
      - mdk2126
      - mlc1
      - mw18
      - mw2064
      - mz84
      - nef4
      - pbg1
      - pm2650
      - pm2650
      - pmg16
      - px2108
      - raw7
      - rd94
      - rf63
      - rhd2106
      - rhs1
      - rkb7
      - rlb179
      - sam119
      - sek26
      - sem2166
      - shs4
      - sk33
      - sn2160
      - sy2133
      - ur2
      - vjs4
      - yl105



