layouts:
  articles:
    style: summon
    # obsolete
    # has_facets: true
    columns:
      - searches:
          - source: articles 
  library_web:
    style: single
    columns:
      - searches:
          - source: library_web 
            # let per-page (row count) be parameterized
            # count: 10
  quicksearch:
    style: aggregate
    columns:
      - width: 6
        searches:
          - source: catalog
            count: 10
            display_footer: true
            row_opts:
              spans: [3,9] 
      - width: 6
        searches:
          - source: articles
            count: 3
            row_opts:
              spans: [3,9] 

          - source: academic_commons
            count: 3
            row_opts:
              spans: [3,9]

          - source: library_web
            count: 3
            row_opts:
              spans: [3,9]

          - source: dcv
            count: 3
            row_opts:
              spans: [3,9] 

  newspapers:
    style: summon
    # obsolete
    # has_facets: true
    columns:
      - searches:
          - source: newspapers 
  dissertations:
    style: aggregate
    columns:
      - width: 6
        searches:
          - source: catalog_dissertations
            count: 10
            display_footer: true
            row_opts:
              spans: [3,9] 
      - width: 6
        searches:
          - source: dissertations
            count: 3
            row_opts:
              spans: [3,9] 
          - source: ac_dissertations 
            count: 3
            row_opts:
              spans: [3,9] 
  ebooks:
    style: aggregate
    columns:
      - width: 6
        searches:
          - source: catalog_ebooks 
            count: 10
            display_footer: true
            row_opts:
              spans: [3,9] 
      - width: 6
        searches:
          - source: ebooks 
            count: 10
            display_footer: true
            row_opts:
              spans: [3,9]


sources:

  quicksearch:
    warning: 

  archives:
    Xwarning:  Due to system maintenance, certain CLIO services will be unavailable beginning at 7pm, Friday, January 3rd.  We expect full service to be restored by Monday morning, January 6th.

  new_arrivals:
    Xwarning:  Due to system maintenance, certain CLIO services will be unavailable beginning at 7pm, Friday, January 3rd.  We expect full service to be restored by Monday morning, January 6th.

  catalog:
    title: Catalog
    description: Library books, journals, music, videos, databases, archival collections, and online resources
    Xwarning:  Due to system maintenance, certain CLIO services will be unavailable beginning at 7pm, Friday, January 3rd.  We expect full service to be restored by Monday morning, January 6th.
    holdings_check: true
    render_options:
      format: clio

  articles:
    title: Articles
    description: Articles, e-books, dissertations, music, images, and more from a mostly full-text database
    warningXX: We are currently experiencing performance problems with this datasource.  We are working with the vendor to resolve this issue.
    render_options:
      format: article

  academic_commons:
    title: Academic Commons
    description: Publications and other research output from Columbia University's digital repository 
    warningXX:  Item Status unavailable due to system upgrades.  AC.
    render_options:
      format: ac
      check_fedora: true

  dcv:
    title: DCV
    description: dcv 
    warningXX:  dcv.
    render_options:
      format: dcv

  library_web:
    title: Libraries Website
    description: Information about the libraries from the Libraries Website
    warningXX:  Item Status unavailable due to system upgrades.  LWEB.
    render_options:
      format: lweb

  ac_dissertations:
    title: Academic Commons
    description: Dissertations deposited in Columbia's digital repository, primarily 2011-present.
    warningXX:  Item Status unavailable due to system upgrades.  AC-DISS.
    render_options:
      format: ac
      check_fedora: true

  dissertations:
    title: Summon
    description: Dissertations and theses from the Articles database. Many are full-text.
    warningXX: We are currently experiencing performance problems with this datasource.  We are working with the vendor to resolve this issue.  ArtyDiss.
    render_options:
      format: article

  newspapers:
    title: Newspaper Articles
    description: Full text newspaper articles from Summon
    warningXX: We are currently experiencing performance problems with this datasource.  We are working with the vendor to resolve this issue.  ArtyNews.
    render_options:
      format: article

  databases:
    title: Databases
    description: Electronic resources
    Xwarning:  Due to system maintenance, certain CLIO services will be unavailable beginning at 7pm, Friday, January 3rd.  We expect full service to be restored by Monday morning, January 6th.
    render_options:
      format: clio

  catalog_dissertations:
    title: Catalog
    description: Dissertations from the library catalog
    warningXX:  Item Status unavailable due to system upgrades.  CAT-DISS.
    render_options:
      format: clio

  catalog_ebooks:
    title: Catalog
    description: E-books from the library catalog
    warningXX:  Item Status unavailable due to system upgrades.  CAT-EBOO.
    render_options:
      format: clio

  journals:
    title: Journal Titles
    description: Electronic Journals Held By Columbia
    Xwarning:  Due to system maintenance, certain CLIO services will be unavailable beginning at 7pm, Friday, January 3rd.  We expect full service to be restored by Monday morning, January 6th.
    render_options:
      format: clio 

  ebooks:
    title: Summon
    description: E-books from the Articles database
    warningXX: We are currently experiencing performance problems with this datasource.  We are working with the vendor to resolve this issue.  eboo.
    render_options:
      format: ebooks


