default_search_layouts:

  articles:
    style: summon
    columns:
      - searches:
          - source: articles 

  library_web:
    style: lweb
    columns:
      - searches:
          - source: library_web 

  lweb:
    style: lweb
    columns:
      - searches:
          - source: lweb 

  ac:
    style: ac
    columns:
      - searches:
          - source: ac 

  quicksearch:
    style: aggregate
    columns:
      - searches:
        - source: catalog
          count: 5
          display_footer: true
        - source: geo
          count: 3
          display_footer: true
      - searches:
        - source: articles
          count: 3
          display_footer: true
        - source: ac
          count: 3
          display_footer: true
        - source: lweb
          count: 3
          display_footer: true

  dissertations:
    style: aggregate
    columns:
      - searches:
          - source: catalog_dissertations
            count: 10
            display_footer: true
      - searches:
          - source: summon_dissertations
            count: 3
          - source: ac_dissertations 
            count: 3

  ebooks:
    style: aggregate
    columns:
      - searches:
          - source: catalog_ebooks 
            count: 10
            display_footer: true
      - searches:
          - source: summon_ebooks 
            count: 10
            display_footer: true

  research_data:
    style: aggregate
    columns:
      - searches:
          - source: catalog_data
            count: 10
            display_footer: true
      - searches:
          - source: ac_data
            count: 3
          - source: geo_cul
            count: 3

